baseURL = "http://blog.phpst.cn"
languageCode = "zh-CN"
title = "徐曙辉个人博客"
theme = "maupassant"
## 保持分类的原始名字（false会做转小写处理）
preserveTaxonomyNames = true
hasCJKLanguage =  true
[author]
  name = "徐曙辉"

[params]
  author = "徐曙辉"
  subtitle = "专注于PHP、Java、Go语言(golang)、移动互联网、项目管理、软件架构"
  keywords = "golang,go语言,go语言笔记,徐曙辉,java,PHP,博客,项目管理,python,软件架构,公众号,小程序"
  description = "专注于IT互联网，包括但不限于Go语言(golang)、Java、PHP、Python、软件架构等"
  localSearch = true
[menu]
  [[menu.main]]
    identifier = "github"
    name = "github"
    url = "https://github.com/xushuhui"
    weight = 5
  [[menu.main]]
    identifier = "archives"
    name = "归档"
    url = "/archives/"
    weight = 3
  [[menu.main]]
    identifier = "about"
    name = "关于"
    url = "/about/"
    weight = 4

[params.utteranc]
  enable = true
  repo = "xushuhui/hugo-comment"
  issueTerm = "pathname"
  theme = "github-light"